### ISSUE TITLE
Decryption of ~/.dropbox/instance1/hostkeys on macOS

### ISSUE THREAD

**Issue by dnicolson** [newsoft/dbx-keygen-macosx#1]
It seems that Dropbox v86.4.146 on macOS stores `hostkeys` files in the following locations:
- `~/.dropbox/instance1/hostkeys`
- `~/.dropbox/instance_db/hostkeys`

Using [Look inside the box](https://github.com/anvilventures/lookinsidethebox) it appears as though only the `DAVolumeUUID` value is used for encryption. The `get_serial_number` method doesn't seem to be called to retrieve the `IOPlatformSerialNumber` value as mentioned in the [analysis](https://asfws12.files.wordpress.com/2012/11/dropbox-asfws-version.pdf).

Amending the [Linux](https://github.com/newsoft/dbx-keygen-linux/blob/master/dbx-keygen-linux.py) version to use the `instance1` path and the UUID in the `unique_id` function returns data that is not JSON.

Is it possible to get the decryption key on macOS?

**Comment by dnicolson** [comment]
It seems that only the legacy implementation used the UUID, removing this simplified things and now it [works](https://github.com/dnicolson/dbx-keygen-macos).

**Comment by newsoft** [comment]
Thank you for letting me know, and Happy New Year ;)
